"""C2R7-B semantic-graph sidecar binding for P0 structural projection.

The relational semantic graph remains first-class and external to Grid81.
This module binds its canonical digest to the structural projection identity
without mapping semantic nodes/edges into cells or granting graph data
structural mutation authority.
"""
from __future__ import annotations

from dataclasses import replace
import hashlib
import json

from .canonical import digest
from .contracts import RequestContext, StructuralProjection
from .projector import DeterministicPythonProjector

P0_SEMANTIC_SIDECAR_BINDING_SCHEMA = (
    "elpis.p0.semantic-sidecar-binding.v1"
)
P0_SEMANTIC_SIDECAR_BINDING_DOMAIN = (
    "elpis.p0.semantic-sidecar-binding.c2r7b.v1"
)


class P0SemanticSidecarBindingError(ValueError):
    pass


def _canonical_bytes(payload: object) -> bytes:
    return json.dumps(
        payload,
        sort_keys=True,
        separators=(",", ":"),
        ensure_ascii=False,
        allow_nan=False,
    ).encode("utf-8")


def _domain_digest(domain: str, payload: object) -> str:
    return hashlib.sha256(
        domain.encode("utf-8")
        + b"\x00"
        + _canonical_bytes(payload)
    ).hexdigest()


def _require_digest(name: str, value: str) -> None:
    if not isinstance(value, str) or len(value) != 64:
        raise P0SemanticSidecarBindingError(
            f"{name} must be a 64-character hexadecimal digest"
        )
    try:
        int(value, 16)
    except ValueError as exc:
        raise P0SemanticSidecarBindingError(
            f"{name} must be a 64-character hexadecimal digest"
        ) from exc


def semantic_sidecar_binding_payload(
    projection: StructuralProjection,
) -> dict[str, object]:
    return {
        "schema": P0_SEMANTIC_SIDECAR_BINDING_SCHEMA,
        "semantic_request_digest": (
            projection.semantic_request_digest
        ),
        "structural_projection_digest": (
            projection.structural_projection_digest
        ),
        "grid81": list(projection.grid81),
        "semantic_rows": list(projection.semantic_rows),
        "features": [
            [name, value]
            for name, value in projection.features
        ],
        "semantic_space": projection.semantic_space,
        "semantic_abi_version": (
            projection.semantic_abi_version
        ),
        "semantic_space_digest": (
            projection.semantic_space_digest
        ),
    }


def semantic_sidecar_binding_digest(
    projection: StructuralProjection,
) -> str:
    return _domain_digest(
        P0_SEMANTIC_SIDECAR_BINDING_DOMAIN,
        semantic_sidecar_binding_payload(projection),
    )


def bound_projection_digest(
    projection: StructuralProjection,
) -> str:
    return digest(
        {
            "binding_schema": (
                P0_SEMANTIC_SIDECAR_BINDING_SCHEMA
            ),
            "semantic_request_digest": (
                projection.semantic_request_digest
            ),
            "structural_projection_digest": (
                projection.structural_projection_digest
            ),
            "semantic_binding_digest": (
                projection.semantic_binding_digest
            ),
        }
    )


def validate_semantic_sidecar_projection(
    projection: StructuralProjection,
) -> None:
    values = (
        projection.semantic_request_digest,
        projection.structural_projection_digest,
        projection.semantic_binding_digest,
    )
    if not any(values):
        return
    if not all(values):
        raise P0SemanticSidecarBindingError(
            "semantic sidecar projection identity must be complete"
        )

    _require_digest(
        "semantic_request_digest",
        projection.semantic_request_digest,
    )
    _require_digest(
        "structural_projection_digest",
        projection.structural_projection_digest,
    )
    _require_digest(
        "semantic_binding_digest",
        projection.semantic_binding_digest,
    )

    expected_binding = semantic_sidecar_binding_digest(
        projection
    )
    if expected_binding != projection.semantic_binding_digest:
        raise P0SemanticSidecarBindingError(
            "semantic sidecar binding digest mismatch"
        )

    expected_projection = bound_projection_digest(
        projection
    )
    if expected_projection != projection.digest:
        raise P0SemanticSidecarBindingError(
            "bound structural projection digest mismatch"
        )


class SemanticSidecarPythonProjector:
    """Explicit semantic-sidecar wrapper around the legacy Grid81 projector.

    For graphless requests, output is exactly the legacy projection.
    For structured requests, Grid81 and feature payloads are generated by the
    unchanged legacy projector over the same RequestContext with the semantic
    graph removed. The graph digest is then bound as a sidecar identity.
    """

    semantic_rows = DeterministicPythonProjector.semantic_rows

    def __init__(self) -> None:
        self._legacy = DeterministicPythonProjector()

    def project(
        self,
        context: RequestContext,
    ) -> StructuralProjection:
        semantic_request = context.semantic_request
        if semantic_request is None:
            return self._legacy.project(context)

        semantic_request.validate()
        if semantic_request.request_id != context.request_id:
            raise P0SemanticSidecarBindingError(
                "structured semantic request_id does not match "
                "RequestContext.request_id"
            )

        legacy_context = replace(
            context,
            semantic_request=None,
        )
        structural = self._legacy.project(legacy_context)
        structural.validate()

        unsigned = StructuralProjection(
            grid81=structural.grid81,
            semantic_rows=structural.semantic_rows,
            features=structural.features,
            digest="",
            semantic_space=structural.semantic_space,
            semantic_abi_version=(
                structural.semantic_abi_version
            ),
            semantic_space_digest=(
                structural.semantic_space_digest
            ),
            semantic_request_digest=(
                semantic_request.digest
            ),
            structural_projection_digest=(
                structural.digest
            ),
            semantic_binding_digest="",
        )
        binding = semantic_sidecar_binding_digest(unsigned)

        bound = StructuralProjection(
            grid81=unsigned.grid81,
            semantic_rows=unsigned.semantic_rows,
            features=unsigned.features,
            digest="",
            semantic_space=unsigned.semantic_space,
            semantic_abi_version=(
                unsigned.semantic_abi_version
            ),
            semantic_space_digest=(
                unsigned.semantic_space_digest
            ),
            semantic_request_digest=(
                unsigned.semantic_request_digest
            ),
            structural_projection_digest=(
                unsigned.structural_projection_digest
            ),
            semantic_binding_digest=binding,
        )
        projection = replace(
            bound,
            digest=bound_projection_digest(bound),
        )
        projection.validate()
        return projection
